# Generated by Django 3.2.8 on 2021-11-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20211102_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Idioma')),
            ],
            options={
                'verbose_name': 'Idioma',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='sumary',
            field=models.TextField(blank=True, verbose_name='Resumen'),
        ),
    ]
